homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

frontend:

config:

http:

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

sensor:
  - platform: yr

tts:
  - platform: google

cloud:

alexa: !include_dir_merge_named alexa
automation: !include_dir_merge_named automation
camera: !include_dir_merge_named cameras
group: !include_dir_merge_named groups
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_named sensors
zone: !include_dir_merge_named zones
